module.exports = {
    'AGUASCALIENTES': 1,
    'BAJA CALIFORNIA': 28,
    'BAJA CALIFORNIA SUR': 5,
    'CAMPECHE': 2,
    'CHIAPAS': 3,
    'CHIHUAHUA': 16,
    'COAHUILA': 12,
    'COLIMA': 0,
    'DURANGO': 3,
    'GUANAJUATO': 5,
    'GUERRERO': 6,
    'HIDALGO': 10,
    'JALISCO': 11,
    'MÉXICO': 35,
    'CIUDAD DE MÉXICO': 92,
    'MICHOACÁN': 11,
    'MORELOS': 9,
    'NAYARIT': 4,
    'NUEVO LEÓN': 5,
    'OAXACA': 5,
    'PUEBLA': 27,
    'QUERETARO': 4,
    'QUINTANA ROO': 25,
    'SAN LUIS POTOSÍ': 4,
    'SINALOA': 34,
    'SONORA': 9,
    'TABASCO': 19,
    'TAMAULIPAS': 3,
    'TLAXCALA': 4,
    'VERACRUZ': 5,
    'YUCATÁN': 7,
    'ZACATECAS': 2
}