module.exports = {
    'AGUASCALIENTES': 0,
    'BAJA CALIFORNIA': 16,
    'BAJA CALIFORNIA SUR': 2,
    'CAMPECHE': 1,
    'CHIAPAS': 0,
    'CHIHUAHUA': 1,
    'COAHUILA': 7,
    'COLIMA': 0,
    'DURANGO': 4,
    'GUANAJUATO': 1,
    'GUERRERO': 5,
    'HIDALGO': 7,
    'JALISCO': 8,
    'MÉXICO': 11,
    'CIUDAD DE MÉXICO': 43,
    'MICHOACÁN': 5,
    'MORELOS': 7,
    'NAYARIT': 3,
    'NUEVO LEÓN': 5,
    'OAXACA': 1,
    'PUEBLA': 10,
    'QUERETARO': 2,
    'QUINTANA ROO': 12,
    'SAN LUIS POTOSÍ': 4,
    'SINALOA': 15,
    'SONORA': 4,
    'TABASCO': 9,
    'TAMAULIPAS': 3,
    'TLAXCALA': 0,
    'VERACRUZ': 3,
    'YUCATÁN': 3,
    'ZACATECAS': 2
}