module.exports = {
    'AGUASCALIENTES': 1,
    'BAJA CALIFORNIA': 28,
    'BAJA CALIFORNIA SUR': 6,
    'CAMPECHE': 2,
    'CHIAPAS': 3,
    'CHIHUAHUA': 20,
    'COAHUILA': 12,
    'COLIMA': 0,
    'DURANGO': 4,
    'GUANAJUATO': 5,
    'GUERRERO': 8,
    'HIDALGO': 12,
    'JALISCO': 11,
    'MÉXICO': 43,
    'CIUDAD DE MÉXICO': 99,
    'MICHOACÁN': 12,
    'MORELOS': 10,
    'NAYARIT': 5,
    'NUEVO LEÓN': 5,
    'OAXACA': 5,
    'PUEBLA': 31,
    'QUERETARO': 5,
    'QUINTANA ROO': 27,
    'SAN LUIS POTOSÍ': 4,
    'SINALOA': 38,
    'SONORA': 9,
    'TABASCO': 21,
    'TAMAULIPAS': 4,
    'TLAXCALA': 4,
    'VERACRUZ': 6,
    'YUCATÁN': 7,
    'ZACATECAS': 2
}