module.exports = {
    'AGUASCALIENTES': 'AG',
    'BAJA CALIFORNIA': 'BC',
    'BAJA CALIFORNIA SUR': 'BS',
    'CAMPECHE': 'CM',
    'CHIAPAS': 'CS',
    'CHIHUAHUA': 'CH',
    'COAHUILA': 'CO',
    'COLIMA': 'CL',
    'DURANGO': 'DG',
    'GUANAJUATO': 'GT',
    'GUERRERO': 'GR',
    'HIDALGO': 'HG',
    'JALISCO': 'JA',
    'MEXICO': 'EM',
    'DISTRITO FEDERAL': 'DF',
    'MICHOACAN': 'MI',
    'MORELOS': 'MO',
    'NAYARIT': 'NA',
    'NUEVO LEON': 'NL',
    'OAXACA': 'OA',
    'PUEBLA': 'PU',
    'QUERETARO': 'QT',
    'QUINTANA ROO': 'QR',
    'SAN LUIS POTOSI': 'SL',
    'SINALOA': 'SI',
    'SONORA': 'SO',
    'TABASCO': 'TB',
    'TAMAULIPAS': 'TM',
    'TLAXCALA': 'TL',
    'VERACRUZ': 'VE',
    'YUCATAN': 'YU',
    'ZACATECAS': 'ZA'
}


